{% set name = "azure-keyvault" %}
{% set version = "4.1.0" %}
{% set sha256 = "69002a546921a8290eb54d9a3805cfc515c321bc1d4c0bfcfb463620245eca40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - azure-common >=1.1,<2
    - cryptography >=2.1.4
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - python
    - requests >=2.18.4

test:
  imports:
    - azure
    - azure.keyvault.certificates
    - azure.keyvault.keys
    - azure.keyvault.secrets

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Key Vault Client Library for Python

  doc_url: https://docs.microsoft.com/en-us/python/api/overview/azure/key-vault
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - andreyz4k
    - pedrolupin
